# Setup
title:            Ossi E. Tahvonen
tagline:          Home
description:      PhD student in <br/> University of Helsinki <br/> ossi.tahvonen@helsinki.fi
url:              https://ossitahvonen.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Ossi Tahvonen'
  url:            https://twitter.com/ossitahvonen

github:
  repo:           https://github.com/ossitahvonen/ossitahvonen.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
